name: CI

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage to PR
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html/

      - name: Check coverage meets threshold
        run: ./gradlew jacocoTestCoverageVerification

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: build/reports/jacoco/test/html/index.html
          recreate: true
          header: coverage-report

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml
          github_token: ${{ github.token }}
